<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FsCheck.Xunit" Version="2.16.6"/>
        <PackageReference Include="LanguageExt.Core" Version="4.4.6"/>
        <PackageReference Include="System.Collections.Immutable" Version="6.0.0"/>
        <PackageReference Include="xunit" Version="2.4.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bits\Bits.fsproj" />
    </ItemGroup>

</Project>
